### ISSUE TITLE
Feature request: set upstream of branches

### ISSUE THREAD

**Issue by JordanLongstaff** [m-hall/vscode-git-branch-sidebar#2]
Hey, I found this extension in the Marketplace, and I know it's going to be incredibly useful! Thanks for it!

One thing I would like to see added to it, though, is a way to re-set the upstream remote branch for a local branch. The reason is because all of my local branches are supposed to be based off of `origin/master`, but sometimes I accidentally publish the changes to a new remote branch and have to manually re-set its upstream remote branch to `origin/master`.

In case you need help knowing how to do this:
https://stackoverflow.com/questions/4878249/how-to-change-the-remote-a-branch-is-tracking

**Comment by m-hall** [comment]
That seems like a reasonable request. I’m currently moving, so it may take a while, but I’ll add it to the list.

**Comment by m-hall** [comment]
Version 1.4.0 now includes the ability to set or delete upstreams for branches.
