### ISSUE TITLE
Feature Request: Checkout & Pull

### ISSUE THREAD

**Issue by Regenhardt** [m-hall/vscode-git-branch-sidebar#7]
I'd like a context menu option to checkout the branch and immediately pull from the remote. This is helpful if you have enough people working on one develop branch. Probably better to wait with this until #6 is merged though I guess since I guess it'd use the API.

**Comment by m-hall** [comment]
With `1.6.0` a couple new options have been added.

Context menu 
 - Sync with remote
 - Sync & Checkout

Thanks @v-mas for adding this <3
